networks:
  mini-chat-back-end:
    name: mini-chat-back-end

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    networks:
      - mini-chat-back-end
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    networks:
      - mini-chat-back-end
    ports:
      - 6379:6379

  express:
    build: .
    restart: always
    env_file: .env
    networks:
      - mini-chat-back-end
    ports:
      - 8000:8000
